### ISSUE TITLE
Formatting Problems: Quote Arrows

### ISSUE THREAD

**Issue by timlangeman** [CiteIt/citeit-wordpress#18]
The arrows surrounding a quotation have [formatting problems](https://www.willnissley.com/2019/12/04/matthew-628/):

<img width="944" alt="Quote-Arrows-Matthew6" src="https://user-images.githubusercontent.com/134813/70107897-db719600-1615-11ea-8b5d-12ca4c34c6ee.png">

**Comment by rajats98** [comment]
I think this issue should not persist after the fix of #19, commit - 5b404353ef56ba635f20f2c7b79773c65d1f58d2.

I guess, The problem was negative margin in div.quote_arrows.context_up from bottom (almost working equivalent to top-margin). As of latest commit I think it is resolved. 

It would be great suggesting to use the updated version  to [user](https://www.willnissley.com/2019/12/04/matthew-628/).

Even if the issue persists after updating, I would love to give it one more try to find any bug.
